version: "3.7"
services:
  opentsdb:
    hostname: otsdb-host
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30    
    ports:
      - 4242:4242
      - 60030:60030
    volumes:
      - "./data:/data/hbase"
  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - opentsdb
    