version: "3.7"
services:
  opentsdb:
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30    
    ports:
      - 4242:4242
      - 60030:60030
    volumes:
      - type: volume
        source: opentsdb-data
        target: /data/hbase
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - opentsdb
volumes:
  opentsdb-data: